### ISSUE TITLE
CUDA out of memory (RTX 3060) 

### ISSUE THREAD

**Issue by ld3z** [n00mkrad/flowframes#139]
I am using FF 1.32.0 with a GeForce RTX 3060 (previously a GTX 1060) and I keep getting this error.

![image](https://user-images.githubusercontent.com/42660576/168923785-82b0549e-5b4d-48c2-a152-336c2ac0269c.png)

I never got this error before on my other card and I can't seem to find a fix, I have tried re-installing and redownloading FF but can't seem to get it fixed. Any ideas to what it can be?

Here's logs too:
```
[0] [5-17-2022 15:31:23]: Command Line: "C:\Users\Usr\AppData\Local\Flowframes\Flowframes.exe" 
[1] [5-17-2022 15:31:23]: Files: None
[2] [5-17-2022 15:31:23]: Args: None
[3] [5-17-2022 15:31:23]: Initialized Nvidia API. GPU: NVIDIA GeForce RTX 3060
[4] [5-17-2022 15:31:23]: SymlinksAllowed: True
[5] [5-17-2022 15:31:23]: Parsing Patrons from CSV...
[6] [5-17-2022 15:31:23]: Found 13 Gold Patrons, 442 Silver Patrons
[7] [5-17-2022 15:31:23]: [Servers] Ping to nmkd-hz.de: 157 ms
[8] [5-17-2022 15:31:23]: [Servers] Ping to nmkd-cb.de: 63 ms
[9] [5-17-2022 15:31:23]: [Servers] Closest Server: nmkd-cb.de (63 ms)
[10] [5-17-2022 15:31:24]: [UI] You are running Flowframes 1.32.0. The latest Patreon version is 1.37.1, the latest free version is 1.32.0.
[11] [5-17-2022 15:31:24]: [GetGpus] Found GPU: NVIDIA GeForce RTX 3060
[12] [5-17-2022 15:31:37]: Selected video/directory: Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v
[13] [5-17-2022 15:31:37]: [UI] Loading metadata...
[16] [5-17-2022 15:31:37]: Getting frame count (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[17] [5-17-2022 15:31:37]: Hash not cached, reading frame count.
[20] [5-17-2022 15:31:37]: Adding hash with value 2640 to cache.
[22] [5-17-2022 15:31:37]: GetFfprobeInfoAsync(C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[23] [5-17-2022 15:31:37]: Getting output for cmd.exe /C cd /D "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\av" & ffprobe -v quiet -show_format -show_streams "C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v"
[24] [5-17-2022 15:31:37]: Output (after 118ms): [STREAM] / index=0 / codec_name=h264 / codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 / profile=Main / codec_type=video / codec_tag_string=avc1 / codec_tag=0x31637661 / width=1408 / height=1080 / coded_width=1408 / coded_height=1080 / clos…
[26] [5-17-2022 15:31:37]: GetFfmpegInfoAsync(C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[27] [5-17-2022 15:31:37]: Getting output for cmd.exe /C cd /D "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\av" & ffmpeg.exe -hide_banner -y -stats -i "C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v"
[28] [5-17-2022 15:31:37]: Output (after 185ms): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v': / Metadata: / major_brand : mp42 / minor_version : 512 / compatible_brands: mp42iso2avc1mp41 / creation_time : …
[30] [5-17-2022 15:31:37]: Converted float 23.99 to Fraction 2399/100
[31] [5-17-2022 15:31:37]: Detected FPS of Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v as 24/1 FPS
[32] [5-17-2022 15:31:37]: [UI] [REPL] Video FPS: 24/1 (~24) - Total Number Of Frames: 2640
[33] [5-17-2022 15:31:37]: Getting media resolution (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[34] [5-17-2022 15:31:37]: Hash not cached, reading resolution.
[37] [5-17-2022 15:31:38]: Detected video size of Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v as 1408x1080
[38] [5-17-2022 15:31:38]: Adding hash with value {Width=1408, Height=1080} to cache.
[39] [5-17-2022 15:31:38]: [UI] Input Resolution: 1408x1080
[44] [5-17-2022 15:31:43]: Failed to parse "Normal Speed" to int: Input string was not in a correct format.
[45] [5-17-2022 15:31:43]: RefreshExtensions(Both) - alpha = False pngOutput = False aviHqChroma = False proresHqChroma = False
[46] [5-17-2022 15:31:43]: RefreshExtensions - Using '.jpg' for imported frames, using '.png' for interpolated frames
[47] [5-17-2022 15:31:43]: SetWorking(True)
[48] [5-17-2022 15:31:43]: Getting frame count (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[49] [5-17-2022 15:31:43]: Cache contains this hash, using cached value.
[50] [5-17-2022 15:31:43]: Starting...
[51] [5-17-2022 15:31:43]: RefreshAlpha: model.supportsAlpha = False - outputSupportsAlpha = False - input ext: .m4v => alpha = False
[52] [5-17-2022 15:31:43]: RefreshExtensions(Import) - alpha = False pngOutput = False aviHqChroma = False proresHqChroma = False
[53] [5-17-2022 15:31:43]: RefreshExtensions - Using '.jpg' for imported frames, using '.png' for interpolated frames
[54] [5-17-2022 15:31:43]: Extracting scenes from video...
[55] [5-17-2022 15:31:43]: [UI] Extracting scene changes...
[56] [5-17-2022 15:31:43]: [UI] Running FFmpeg...
[68] [5-17-2022 15:31:46]: [UI] [REPL] Detected 348 scene changes.
[69] [5-17-2022 15:31:46]: Extracting frames from video...
[70] [5-17-2022 15:31:46]: RefreshExtensions(Import) - alpha = False pngOutput = False aviHqChroma = False proresHqChroma = False
[71] [5-17-2022 15:31:46]: RefreshExtensions - Using '.jpg' for imported frames, using '.png' for interpolated frames
[72] [5-17-2022 15:31:46]: Getting media resolution (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[73] [5-17-2022 15:31:46]: Cache contains this hash, using cached value.
[74] [5-17-2022 15:31:46]: [UI] Extracting video frames from input video...
[76] [5-17-2022 15:31:46]: [UI] Running FFmpeg...
[94] [5-17-2022 15:31:53]: Disk space check for 'C:/': 49.9 GB free.
[105] [5-17-2022 15:31:57]: [UI] [REPL] Extracted 2640 frames from input.
[106] [5-17-2022 15:31:57]: Processing frames...
[107] [5-17-2022 15:31:58]: [UI] Generating frame order information...
[108] [5-17-2022 15:31:58]: [UI] [REPL] Generating frame order information for 4x...
[109] [5-17-2022 15:31:58]: [UI] [REPL] Generating frame order information... Done.
[110] [5-17-2022 15:31:58]: Generated frame order info file in 42 ms
[111] [5-17-2022 15:31:58]: Downloading models...
[112] [5-17-2022 15:31:58]: DownloadModelFiles(string ai = Flowframes.Data.AI, string model = RIFE31, bool log = True)
[113] [5-17-2022 15:31:58]: Computed CRC32 for 'contextnet.pkl' (4.6 MB): 2902823721 (26ms)
[114] [5-17-2022 15:31:58]: Computed CRC32 for 'flownet.pkl' (17.4 MB): 675923724 (99ms)
[115] [5-17-2022 15:31:58]: Computed CRC32 for 'IFNet_HDv3.py' (3.1 KB): 3470696862 (0ms)
[116] [5-17-2022 15:31:58]: Computed CRC32 for 'loss.py' (4.7 KB): 3073309973 (0ms)
[117] [5-17-2022 15:31:58]: Computed CRC32 for 'RIFE_HDv3.py' (9.6 KB): 526832239 (14ms)
[118] [5-17-2022 15:31:59]: Computed CRC32 for 'unet.pkl' (45.2 MB): 1449853313 (325ms)
[119] [5-17-2022 15:31:59]: Computed CRC32 for 'warplayer.py' (1.1 KB): 2991145185 (0ms)
[120] [5-17-2022 15:31:59]: Model RIFE31 has architecture python files - copying to arch.
[121] [5-17-2022 15:31:59]: Getting media resolution (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[122] [5-17-2022 15:31:59]: Cache contains this hash, using cached value.
[123] [5-17-2022 15:31:59]: Starting GetProgressByFrameAmount() loop for outdir 'C:\Users\Usr\Videos\Onepiecedub-Op1Waifu2x1920X108-temp\interp', target is 10557 frames
[124] [5-17-2022 15:31:59]: [UI] Using embedded Python runtime.
[125] [5-17-2022 15:31:59]: Getting media resolution (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[126] [5-17-2022 15:31:59]: Cache contains this hash, using cached value.
[127] [5-17-2022 15:31:59]: [UI] Running RIFE (CUDA)...
[128] [5-17-2022 15:31:59]: cmd.exe /C cd /D "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\rife-cuda" & set CUDA_VISIBLE_DEVICES=0 & "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\python.exe" -u rife.py --input "C:\Users\Usr\Videos\Onepiecedub-Op1Waifu2x1920X108-temp\frames" --output interp --model RIFE31 --exp 2 --wthreads 8 --rbuffer 200 
[129] [5-17-2022 15:31:59]: Running RIFE (CUDA)... (Using Auto-Encode)
[130] [5-17-2022 15:31:59]: [AE] Starting AutoEncode MainLoop - Chunk Size: 600 Frames - Safety Buffer: 90 Frames
[131] [5-17-2022 15:31:59]: Running AI...
[138] [5-17-2022 15:32:8]: Disk space check for 'C:/': 49.7 GB free.
[169] [5-17-2022 15:32:19]: [UI] Interpolated 0/10557 Frames (0%) - Average Speed: 0.00 FPS In / 0.00 FPS Out - Time: 20s - ETA: 08s
[170] [5-17-2022 15:32:19]: Creating output video from frames...
[171] [5-17-2022 15:32:19]: [UI] Done running RIFE - Interpolation took 20s. Peak Output FPS: 0.00 - Waiting for encoding to finish...
[172] [5-17-2022 15:32:19]: Canceled.
[173] [5-17-2022 15:32:19]: SetWorking(False)
[174] [5-17-2022 15:32:19]: [UI] Canceled interpolation.
[175] [5-17-2022 15:32:19]: [BgTaskMgr] Task 'TryDeleteIfExistsAsync C:\Users\Usr\Videos\Onepiecedub-Op1Waifu2x1920X108-temp_' has finished after 345ms (Timeout 120s)
[176] [5-17-2022 15:33:36]: Message: Your GPU ran out of VRAM! Please try a video with a lower resolution or use the Max Video Size option in the settings. [E] RuntimeError: CUDA out of memory. Tried to allocate 8.13 GiB (GPU 0; 12.00 GiB total capacity; 411.54 MiB already allocated; 9.19 GiB free; 988.00 MiB reserved in total by PyTorch)
[177] [5-17-2022 15:33:36]: Canceled.
[178] [5-17-2022 15:33:36]: SetWorking(False)
[179] [5-17-2022 15:33:36]: [BgTaskMgr] Task 'TryDeleteIfExistsAsync C:\Users\Usr\Videos\Onepiecedub-Op1Waifu2x1920X108-temp' has finished after 0ms (Timeout 120s)
[180] [5-17-2022 15:33:37]: Message: Canceled: Interpolation failed - No interpolated frames were created. Last 10 log lines: [E] result = self.forward(*input, **kwargs) [E] File "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\Lib\site-packages\torch\nn\modules\container.py", line 117, in forward [E] input = module(input) [E] File "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\Lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl [E] result = self.forward(*input, **kwargs) [E] File "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\Lib\site-packages\torch\nn\modules\conv.py", line 423, in forward [E] return self._conv_forward(input, self.weight) [E] File "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\Lib\site-packages\torch\nn\modules\conv.py", line 419, in _conv_forward [E] return F.conv2d(input, weight, self.bias, self.stride, [E] RuntimeError: CUDA out of memory. Tried to allocate 8.13 GiB (GPU 0; 12.00 GiB total capacity; 411.54 MiB already allocated; 9.19 GiB free; 988.00 MiB reserved in total by PyTorch) Check the log 'rife-cuda-log' for more details.
[181] [5-17-2022 15:36:59]: Failed to parse "Normal Speed" to int: Input string was not in a correct format.
[182] [5-17-2022 15:36:59]: RefreshExtensions(Both) - alpha = False pngOutput = False aviHqChroma = False proresHqChroma = False
[183] [5-17-2022 15:36:59]: RefreshExtensions - Using '.jpg' for imported frames, using '.png' for interpolated frames
[184] [5-17-2022 15:36:59]: SetWorking(True)
[185] [5-17-2022 15:36:59]: Getting frame count (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[186] [5-17-2022 15:36:59]: Cache contains this hash, using cached value.
[187] [5-17-2022 15:36:59]: Starting...
[188] [5-17-2022 15:36:59]: RefreshAlpha: model.supportsAlpha = False - outputSupportsAlpha = False - input ext: .m4v => alpha = False
[189] [5-17-2022 15:36:59]: RefreshExtensions(Import) - alpha = False pngOutput = False aviHqChroma = False proresHqChroma = False
[190] [5-17-2022 15:36:59]: RefreshExtensions - Using '.jpg' for imported frames, using '.png' for interpolated frames
[191] [5-17-2022 15:36:59]: Extracting scenes from video...
[192] [5-17-2022 15:36:59]: [UI] Extracting scene changes...
[193] [5-17-2022 15:36:59]: [UI] Running FFmpeg...
[205] [5-17-2022 15:37:2]: [UI] [REPL] Detected 348 scene changes.
[206] [5-17-2022 15:37:2]: Extracting frames from video...
[207] [5-17-2022 15:37:2]: RefreshExtensions(Import) - alpha = False pngOutput = False aviHqChroma = False proresHqChroma = False
[208] [5-17-2022 15:37:2]: RefreshExtensions - Using '.jpg' for imported frames, using '.png' for interpolated frames
[209] [5-17-2022 15:37:2]: Getting media resolution (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[210] [5-17-2022 15:37:2]: Cache contains this hash, using cached value.
[211] [5-17-2022 15:37:2]: [UI] Extracting video frames from input video...
[213] [5-17-2022 15:37:2]: [UI] Running FFmpeg...
[229] [5-17-2022 15:37:8]: Disk space check for 'C:/': 49.9 GB free.
[242] [5-17-2022 15:37:13]: [UI] [REPL] Extracted 2640 frames from input.
[243] [5-17-2022 15:37:13]: Processing frames...
[244] [5-17-2022 15:37:14]: [UI] Generating frame order information...
[245] [5-17-2022 15:37:14]: [UI] [REPL] Generating frame order information for 4x...
[246] [5-17-2022 15:37:14]: [UI] [REPL] Generating frame order information... Done.
[247] [5-17-2022 15:37:14]: Generated frame order info file in 50 ms
[248] [5-17-2022 15:37:14]: Downloading models...
[249] [5-17-2022 15:37:14]: DownloadModelFiles(string ai = Flowframes.Data.AI, string model = RIFE31, bool log = True)
[250] [5-17-2022 15:37:14]: Computed CRC32 for 'contextnet.pkl' (4.6 MB): 2902823721 (7ms)
[251] [5-17-2022 15:37:14]: Computed CRC32 for 'flownet.pkl' (17.4 MB): 675923724 (26ms)
[252] [5-17-2022 15:37:14]: Computed CRC32 for 'IFNet_HDv3.py' (3.1 KB): 3470696862 (0ms)
[253] [5-17-2022 15:37:14]: Computed CRC32 for 'loss.py' (4.7 KB): 3073309973 (0ms)
[254] [5-17-2022 15:37:14]: Computed CRC32 for 'RIFE_HDv3.py' (9.6 KB): 526832239 (0ms)
[255] [5-17-2022 15:37:14]: Computed CRC32 for 'unet.pkl' (45.2 MB): 1449853313 (68ms)
[256] [5-17-2022 15:37:14]: Computed CRC32 for 'warplayer.py' (1.1 KB): 2991145185 (0ms)
[257] [5-17-2022 15:37:14]: Model RIFE31 has architecture python files - copying to arch.
[258] [5-17-2022 15:37:14]: Getting media resolution (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[259] [5-17-2022 15:37:14]: Cache contains this hash, using cached value.
[260] [5-17-2022 15:37:14]: Starting GetProgressByFrameAmount() loop for outdir 'C:\Users\Usr\Videos\Onepiecedub-Op1Waifu2x1920X108-temp\interp', target is 10557 frames
[261] [5-17-2022 15:37:14]: [UI] Using embedded Python runtime.
[262] [5-17-2022 15:37:14]: Getting media resolution (C:\Users\Usr\Videos\Onepiecedub-Op1 Waifu2x 1920X1080 2N Webm-1.m4v)
[263] [5-17-2022 15:37:14]: Cache contains this hash, using cached value.
[264] [5-17-2022 15:37:14]: [UI] Running RIFE (CUDA)...
[265] [5-17-2022 15:37:14]: cmd.exe /C cd /D "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\rife-cuda" & set CUDA_VISIBLE_DEVICES=0 & "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\python.exe" -u rife.py --input "C:\Users\Usr\Videos\Onepiecedub-Op1Waifu2x1920X108-temp\frames" --output interp --model RIFE31 --exp 2 --wthreads 8 --rbuffer 200 
[266] [5-17-2022 15:37:14]: Running RIFE (CUDA)... (Using Auto-Encode)
[267] [5-17-2022 15:37:14]: [AE] Starting AutoEncode MainLoop - Chunk Size: 600 Frames - Safety Buffer: 90 Frames
[268] [5-17-2022 15:37:14]: Running AI...
[305] [5-17-2022 15:37:20]: [UI] Interpolated 0/10557 Frames (0%) - Average Speed: 0.00 FPS In / 0.00 FPS Out - Time: 05s - ETA: 08s
[306] [5-17-2022 15:37:20]: Creating output video from frames...
[307] [5-17-2022 15:37:20]: [UI] Done running RIFE - Interpolation took 05s. Peak Output FPS: 0.00 - Waiting for encoding to finish...
[308] [5-17-2022 15:37:20]: Canceled.
[309] [5-17-2022 15:37:20]: SetWorking(False)
[310] [5-17-2022 15:37:20]: [UI] Canceled interpolation.
[311] [5-17-2022 15:37:20]: [BgTaskMgr] Task 'TryDeleteIfExistsAsync C:\Users\Usr\Videos\Onepiecedub-Op1Waifu2x1920X108-temp_' has finished after 374ms (Timeout 120s)
[312] [5-17-2022 15:40:13]: Message: Your GPU ran out of VRAM! Please try a video with a lower resolution or use the Max Video Size option in the settings. [E] RuntimeError: CUDA out of memory. Tried to allocate 8.13 GiB (GPU 0; 12.00 GiB total capacity; 411.54 MiB already allocated; 9.19 GiB free; 988.00 MiB reserved in total by PyTorch)
[313] [5-17-2022 15:40:13]: Canceled.
[314] [5-17-2022 15:40:13]: SetWorking(False)
[315] [5-17-2022 15:40:13]: [BgTaskMgr] Task 'TryDeleteIfExistsAsync C:\Users\Usr\Videos\Onepiecedub-Op1Waifu2x1920X108-temp' has finished after 0ms (Timeout 120s)
[316] [5-17-2022 15:40:15]: Message: Canceled: Interpolation failed - No interpolated frames were created. Last 10 log lines: [E] result = self.forward(*input, **kwargs) [E] File "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\Lib\site-packages\torch\nn\modules\container.py", line 117, in forward [E] input = module(input) [E] File "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\Lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl [E] result = self.forward(*input, **kwargs) [E] File "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\Lib\site-packages\torch\nn\modules\conv.py", line 423, in forward [E] return self._conv_forward(input, self.weight) [E] File "C:\Users\Usr\AppData\Local\Flowframes\FlowframesData\pkgs\py-amp\Lib\site-packages\torch\nn\modules\conv.py", line 419, in _conv_forward [E] return F.conv2d(input, weight, self.bias, self.stride, [E] RuntimeError: CUDA out of memory. Tried to allocate 8.13 GiB (GPU 0; 12.00 GiB total capacity; 411.54 MiB already allocated; 9.19 GiB free; 988.00 MiB reserved in total by PyTorch) Check the log 'rife-cuda-log' for more details.
```

**Comment by ld3z** [comment]
Apparently it works now, I guess it might have something to do with Virtualization? It was off before and I turned it on to use a virtual machine and now it works? Not sure if this fixes the entire issue though...

**Comment by ld3z** [comment]
Nevermind, it seems to work with 720p video but not 1080p. Which is funny since my old GTX 1060 could do 1080p easy...

**Comment by mirh** [comment]
Try to adjust tile sizing or number of threads?
